[package]
name = "zksync_eigenda_proxy"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
rlp.workspace = true
rand.workspace = true
sha3.workspace = true
zksync_config.workspace = true
# we can't use the workspace version of prost because
# the tonic dependency requires a hugher version.
prost = "0.13.1"
tonic = { version = "0.12.1", features = ["tls", "channel", "tls-native-roots"]}
tonic-web = "0.12.1"
kzgpad-rs = { git = "https://github.com/Layr-Labs/kzgpad-rs.git", tag = "v0.1.0" }
rustls.workspace = true
futures.workspace = true
secp256k1.workspace = true
hex.workspace = true
tokio-stream = "0.1.16"
byteorder = "1.5.0"
tiny-keccak.workspace = true

[build-dependencies]
tonic-build = { version = "0.12.1", features = ["prost"] }
