[chain.state_keeper]
compute_overhead_part=1.0
pubdata_overhead_part=0.0
batch_overhead_l1_gas=1000000
max_pubdata_per_batch=1000000000000
fee_model_version="V2"
l1_batch_commit_data_generator_mode="Validium"

# This override will be removed soon but it is needed for now.
[eth_sender.gas_adjuster]
l1_gas_per_pubdata_byte=0

[_metadata]
base = ['dev.toml']
