[package]
name = "zksync_base_token_fetcher"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_config.workspace = true
zksync_protobuf_config.workspace = true
zksync_dal.workspace = true
vlog.workspace = true
metrics.workspace = true

tokio = { workspace = true, features = ["time"] }
anyhow.workspace = true
async-trait.workspace = true
bigdecimal.workspace = true

reqwest = { workspace = true, features = ["blocking", "json"] }
hex.workspace = true
tracing.workspace = true
