[package]
name = "zksync_base_token_price_fetcher"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_dal.workspace = true

anyhow.workspace = true
tokio = { workspace = true, features = ["rt", "time"] }
tracing.workspace = true
