__imports__ = [ "base", "l1-inits/.init.env", "l2-inits/dev.init.env" ]

ETH_SENDER_SENDER_PUBDATA_SENDING_MODE = "Blobs"

# Configuration for the prometheus exporter server.
[api.prometheus]
listener_port = 3321
pushgateway_url = "http://127.0.0.1:9100"

# Configuration for the healtcheck server.
[api.healthcheck]
port = 3088

# Configuration for the Merkle tree API server
[api.merkle_tree]
port = 3089