__imports__ = [ "base", "l1-inits/.init.env", "l2-inits/main_demo_validium_calldata.init.env" ]

ETH_SENDER_SENDER_PUBDATA_SENDING_MODE = "Calldata"

[chain.state_keeper]
transaction_slots=5000
block_commit_deadline_ms=1800000
max_pubdata_per_batch=100000     # 1 blob max
l1_batch_commit_data_generator_mode="Validium"

[eth_sender.gas_adjuster]
internal_enforced_l1_gas_price=45000000000

[eth_sender.sender]
pubdata_sending_mode="Calldata"

[_metadata]
base=['dev_validium.toml']
