[package]
name = "zksync_server"
description = "ZKsync validator/sequencer node"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
zksync_config = { workspace = true, features = ["observability_ext"] }
zksync_env_config.workspace = true
zksync_eth_client.workspace = true
zksync_protobuf_config.workspace = true
zksync_storage.workspace = true
zksync_utils.workspace = true
zksync_types.workspace = true
zksync_core_leftovers.workspace = true
zksync_node_genesis.workspace = true
zksync_default_da_clients.workspace = true

# Consensus dependenices
zksync_consensus_crypto.workspace = true
zksync_consensus_roles.workspace = true
zksync_consensus_executor.workspace = true
zksync_concurrency.workspace = true
zksync_vlog.workspace = true

anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true

zksync_node_framework.workspace = true
zksync_metadata_calculator.workspace = true
zksync_node_api_server.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator.workspace = true

# avail_client = { version = "0.1.0", git = "https://github.com/matter-labs/hyperchain-da", rev = "d8194ca6f1adcb26507252f21bcce704e35c18d6", optional = true }
# celestia_client = { version = "0.1.0", git = "https://github.com/matter-labs/hyperchain-da", rev = "d8194ca6f1adcb26507252f21bcce704e35c18d6", optional = true }
avail_client = { path = "../../../../hyperchain-da-eigenda/clients/implementations/avail", optional = true }
celestia_client = { path = "../../../../hyperchain-da-eigenda/clients/implementations/celestia", optional = true }
eigen_da_client = { path = "../../../../hyperchain-da-eigenda/clients/implementations/eigenda", optional = true }

[features]
da-celestia = ["celestia_client"]
da-avail = ["avail_client"]
da-eigen = ["eigen_da_client"]

